/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tom' at '17/09/15 11:08 PM' with Gradle 2.6
 *
 * @author tom, @date 17/09/15 11:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
